
import * as azdev from 'azure-devops-node-api';
import * as branch from 'git-branch';
import * as vscode from 'vscode';
import { GitPullRequest } from 'azure-devops-node-api/interfaces/GitInterfaces';
import { TeamContext } from 'azure-devops-node-api/interfaces/CoreInterfaces';
import Utils from "../utils";
import * as _ from 'underscore';
import { WorkItem } from 'azure-devops-node-api/interfaces/WorkItemTrackingInterfaces';
import * as ncp from 'copy-paste';

export default class VSTS {
    private connection: azdev.WebApi;
    private repository: string;
    private orgUrl: string;
    private project: string;

    constructor() {
        const token = vscode.workspace.getConfiguration("fle").ftsToken;
        this.orgUrl = vscode.workspace.getConfiguration("fle").tfsUrl;
        this.repository = vscode.workspace.getConfiguration("fle").ftsRepository;
        this.project = vscode.workspace.getConfiguration("fle").ftsProject;
        const authHandler = azdev.getPersonalAccessTokenHandler(token);
        this.connection = new azdev.WebApi(this.orgUrl, authHandler, { ignoreSslError: true });
    }


    public getAssociateTask() {
        vscode.window.withProgress({ location: vscode.ProgressLocation.Window },
           () => this.connection.getWorkItemTrackingApi().then((work)=>{
               const wiqlQuery = `SELECT [System.Id], [System.WorkItemType], [System.Title], [System.State], [System.AreaPath], [System.IterationPath], [System.Tags] FROM WorkItems WHERE [System.TeamProject] = @project AND [System.AssignedTo] = @me ORDER BY [System.ChangedDate] DESC`;
               return work.queryByWiql({ query: wiqlQuery }, { project: this.project } as TeamContext).then((workItemQueryResult) => {
                  return work.getWorkItems(workItemQueryResult.workItems.map((wi)=> wi.id));
               });
           })
        ).then((workItems: WorkItem[]) => {
            const workItemsMapped = _.map(workItems, (item) => `${item.fields['System.WorkItemType']} ${item.id}: ${item.fields['System.Title']}`);
            // Task 12911: Test A
            vscode.window.showQuickPick(workItemsMapped).then((selectedWorkItemResult) => {
                if (selectedWorkItemResult) {
                    ncp.copy(selectedWorkItemResult);
                    vscode.window.showInformationMessage(selectedWorkItemResult + ' Copied!');
                }
            });
        }, (error) => {
            vscode.window.showErrorMessage('Fail to get associate tasks');
        });
    }

    public createPullRequest() {
        if (vscode.workspace.workspaceFolders) {
            const actualBranchName = branch.sync(vscode.workspace.workspaceFolders[0].uri.fsPath);
            const title = actualBranchName;
            const sourceRefName = 'refs/heads/' + actualBranchName;
            const targetRefName = 'refs/heads/' + actualBranchName.split('/')[0] + '/story';
            const description = `PR: Merge ${sourceRefName} to ${targetRefName} Generated by vscode.`;
            vscode.window.withProgress({
                location: vscode.ProgressLocation.Window },
                () => this.createPullRequestRequest({
                    title,
                    targetRefName,
                    sourceRefName,
                    description
                })
            ).then((pullRequest) => {
                vscode.window.showInformationMessage("Pull request successfully created", 'Open').then((button) => {
                    if(button) {
                        //https://sbatfs06/2Ring/!ProductBacklog-Blue/!ProductBacklog-Blue%20Team/_git/FinesseGadgets/pullrequest/4111#_a=overview
                        const newPrUrl = `${this.orgUrl}/${this.project}/${this.project} Team/_git/${this.repository}/pullrequest/${pullRequest.pullRequestId}`;
                        Utils.OpenUrl(newPrUrl);
                    }
                });
            }, (error) => {
                vscode.window.showErrorMessage('Fail to create pull request: ' + error);
            });
        }
    }

    public openCurrentIterationBoard() {
        vscode.window.withProgress({
            location: vscode.ProgressLocation.Window },
            () => this.getTeamIterations()
        ).then((teamIterations) => {
            // https://sbatfs06/2Ring/!ProductBacklog-Blue/!ProductBacklog-Blue%20Team/_backlogs/TaskBoard/Sprint%2057
            const lastIteration = _.last(teamIterations);
            if (lastIteration) {
                const boardIterationUrl = `${this.orgUrl}/${this.project}/${this.project} Team/_backlogs/TaskBoard/${lastIteration.name}`;
                Utils.OpenUrl(boardIterationUrl);
            }
        },(error) => {
            vscode.window.showErrorMessage('Fail to open current iteration board: ' + error);
        });
    }

    private async getTeamIterations() {
        return await this.connection.getWorkApi().then((workItem) => workItem.getTeamIterations(({ project: this.project }) as TeamContext));
    }

    private async createPullRequestRequest(pullRequestObject: any) {
        return await this.connection.getGitApi().then((git) => git.createPullRequest(pullRequestObject as GitPullRequest, this.repository, this.project));
    }
}
